site_name: Testcontainers for .NET
site_url: https://dotnet.testcontainers.org
repo_name: testcontainers-dotnet
repo_url: https://github.com/testcontainers/testcontainers-dotnet
edit_uri: edit/develop/docs/
theme:
  name: material
  custom_dir: docs/theme
  palette:
    scheme: testcontainers
  font:
    text: Roboto
    code: Roboto Mono
  favicon: favicon.ico
  logo: logo.svg
extra_css:
  - css/extra.css
  - css/tc-header.css
plugins:
  - codeinclude
  - markdownextradata
  - search
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - index.md
  - cicd/index.md
  - custom_configuration/index.md
  - api/create_docker_image.md
  - api/create_docker_container.md
  - api/create_docker_network.md
  - api/resource-reaper.md
  - api/wait_strategies.md
  - api/best_practices.md
  - Examples:
    - examples/dind.md
    - examples/aspnet.md
  - Modules:
    - modules/index.md
    - modules/postgres.md
    - modules/rabbitmq.md
